port: 4222
max_payload: 10485760
# Username/password auth
authorization {
  users = [
    { user: "msight", password: "RatOxTigerRabbitDragonSnakeHorseSheep",
      permissions: {
        publish:   [">"]
        subscribe: [">"]
      }
    }
  ]
}

# TLS enabled (server presents cert; clients verify it)
tls {
  cert_file: "/etc/nats/certs/server.crt"
  key_file:  "/etc/nats/certs/server.key"
  ca_file:   "/etc/nats/certs/ca.crt"   # for clients that trust your private CA; recommended with self-signed CA

  # IMPORTANT: do NOT set verify / verify_and_map => no client cert required
  # verify: true
  # verify_and_map: true
}
