# --- ACL ---
aclfile /usr/local/etc/redis/users.acl

# --- TLS only ---
port 0
tls-port 6380

tls-cert-file /usr/local/etc/redis/certs/server.crt
tls-key-file  /usr/local/etc/redis/certs/server.key
tls-ca-cert-file /usr/local/etc/redis/certs/ca.crt

tls-auth-clients no

protected-mode yes